apiVersion: v1
kind: Service
metadata:
  name: primary-lb
  namespace: values
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: values-mongodb-0
  ports:
  - protocol: TCP
    port: 27017
    name: mongoport
    targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: secondary1-lb
  namespace: values
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: values-mongodb-1
  ports:
  - protocol: TCP
    port: 27017
    name: mongoport
    targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: secondary2-lb
  namespace: values
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: values-mongodb-2
  ports:
  - protocol: TCP
    port: 27017
    name: mongoport
    targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: arbiter-lb
  namespace: values
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: values-mongodb-arbiter-0
  ports:
  - protocol: TCP
    port: 27017
    name: mongoport
    targetPort: 27017    